### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by Adam-Schlichtmann**
### What problem are you trying to solve with this PR?

Spelling

### CODE REVIEW

**Comment by nathanHotz** [comment]
lolz I realized im still on these repos. whoops! Hope all is well with you guys!

**Comment by Renddslow** [comment]
Whoo!  It's like a class reunion! Keep up the good work y'all

**Comment by ParksCF** [comment]
Really proud of your efforts

**Comment by MitchellSlavik** [comment]
👋

**Pull request merged**
